Repository acikkaynak/deprem-yardim-frontend, pull requests merged in 2023-02, with the labels that each got.

#404 fix: Zoom out button fix #417
  components/UI/Map/LeafletMap.tsx
Labels: wip

#413 Feature: Adding a new Button to trigger the API request #407
  components/UI/FooterBanner/FooterBanner.tsx
  pages/index.tsx
Labels: wip

#474 feat: Leaflet Hash'in kullanılması #431
  components/UI/Map/LeafletMap.tsx
Labels: question

#475 feat: Implement incremental request throttling #453
  hooks/useIncrementalThrottling.ts
  pages/index.tsx
  styles/Home.module.css
  utils/constants.ts
Labels: help wanted, wip

#480 fix: cluster popup ui responsivity fix #454
  components/UI/Button/CopyButton.tsx
  components/UI/ClusterPopup/ClusterPopup.tsx
  components/UI/Drawer/Drawer.tsx
  components/UI/Tag/Tag.types.ts
  pages/index.tsx
Labels: wip, kurala-uygun-pr

#515 feat(499): sag alttaki logonun kaldirilmasi
  components/UI/FooterBanner/FooterBanner.tsx
Labels: kurala-uygun-pr

#492 feat: (map redirections) harita yonlendirmeleri marker implementasyonu (feat: #479)
  components/UI/Drawer/Drawer.tsx
Labels: kurala-uygun-pr

#493 issue: "prefix(#451): feat: Sağ üst köşeye diğer sitelerin iconları koyulacak"
  .gitignore
  .hintrc
  .lintstagedrc.js
  components/UI/SitesIcon/Icons.module.css
  components/UI/SitesIcon/Icons.tsx
  package.json
  pages/index.tsx
  public/icons/depremIOIcon.svg
  public/icons/depremyardımIcon.svg
  public/icons/discordIcon.svg
Labels: kurala-uygun-pr

#524 fix(#523): cluster popup zoom fix on clusterpopup component
  components/UI/ClusterPopup/ClusterPopup.tsx
  components/UI/Drawer/Drawer.tsx
  components/UI/FooterBanner/FooterBanner.tsx
  hooks/useDisableZoom.ts
Labels: kurala-uygun-pr

#537 feat(#534): html lang property to tr
  pages/_document.tsx
Labels: kurala-uygun-pr

#554 fix: changes on footer banner height & width, letter spacing #542
  components/UI/FooterBanner/FooterBanner.module.css
Labels: kurala-uygun-pr

#531 feat(#472): yukleniyor ile alani tara butonunu birlestir
  components/UI/Button/LoadArea.tsx
  components/UI/Common/LoadingSpinner.module.css
  components/UI/Common/LoadingSpinner.tsx
  pages/index.tsx
  styles/Home.module.css
Labels: kurala-uygun-pr

#551 feat (#538): added time ago label in the drawer component
  components/UI/Drawer/Drawer.module.css
  components/UI/Drawer/Drawer.tsx
  utils/date.ts
Labels: kurala-uygun-pr

#544 fix (#541): Google Maps loc parametresinin kaldirilmasi
  components/UI/Drawer/Drawer.tsx
Labels: kurala-uygun-pr

#527 fix(#484): UI'da halt/freeze sorunu
  components/UI/Map/LeafletMap.tsx
Labels: kurala-uygun-pr

#563 docs(#513): english version of çabucak-ogren.md
  çabucak-ogren_ENG.md
Labels: kurala-uygun-pr

#562 fix(#536): website link description fixes
  components/UI/SitesIcon/Icons.tsx
Labels: kurala-uygun-pr

#539 refactor(#518): reduce duplicate type usage
  components/UI/Drawer/Drawer.tsx
  mocks/types.ts
  pages/index.tsx
  stores/mapStore.tsx
Labels: kurala-uygun-pr

#576 feat(new link): added afetbilgi.com to top links #570
  components/UI/SitesIcon/Icons.tsx
Labels: kurala-uygun-pr

#589 fix (#482): Tweet yüklenirken çıkan loading tweet metni düzeltilmesi
  components/UI/Drawer/Drawer.tsx
  components/UI/Drawer/components/EmbedTweet.tsx
  components/UI/Drawer/components/PlaceholderTweet.tsx
  components/UI/Drawer/components/TwitterLogo.tsx
  mocks/TypesAreasEndpoint.ts
  package.json
  yarn.lock
Labels: kurala-uygun-pr

#582 fix (#578): Otomatik tarama guncel koordinatlari request de eklemiyor
  pages/index.tsx
Labels: kurala-uygun-pr

#596 fix(#592): GoogleTranslate'in engellenmesi
  pages/_document.tsx
  pages/index.tsx
Labels: kurala-uygun-pr

#599 Drawer'a tweet içeriği sığmadığı için detay görünemiyordu, artık tamamen scrollable. fixes #591
  components/UI/Drawer/Drawer.tsx
Labels: kurala-uygun-pr

#600 fix(#583): adjust default zoom levels to fit affected area
  components/UI/Map/utils.ts
Labels: kurala-uygun-pr

#612 fix(#598): google maps adresi kopyalarken geolocation info ekranının kapanması
  hooks/useMapClickHandlers.ts
Labels: kurala-uygun-pr

#608 feat(#566) fix: align center and change style for scanning text
  pages/index.tsx
  styles/Home.module.css
Labels: kurala-uygun-pr

#614 feat(#613): Add Lighthouse results for preview URLs to pull requests
  .github/workflows/lighthouse-audit.yaml
Labels: kurala-uygun-pr

#621 feat: Add Lighthouse results for preview URLs to pull requests
  .github/workflows/lighthouse-audit.yaml
Labels: kurala-uygun-pr

#625 fix: change mask background to transparent for afetBilgi
  components/UI/SitesIcon/Icons.tsx
Labels: kurala-uygun-pr

#627 feat: Add Lighthouse results for preview URLs to pull requests
  .github/workflows/lighthouse-audit.yaml
Labels: kurala-uygun-pr

#516 feat(#435): seo metatagleri için hazırlanan component markerlara bağlandı
  components/UI/ClusterPopup/ClusterPopup.tsx
  components/UI/Common/LoadingSpinner.tsx
  components/UI/Common/TechnicalError.tsx
  components/UI/Drawer/Drawer.tsx
  components/UI/Drawer/components/EmbedTweet.tsx
  components/UI/Drawer/components/PlaceholderTweet.tsx
  components/UI/Map/ClusterGroup.tsx
  components/UI/Map/DynamicMap.tsx
  components/UI/Map/LayerControl.tsx
  components/UI/Map/LeafletMap.tsx
  components/UI/SitesIcon/Icons.tsx
  components/base/HeadWithMeta/HeadWithMeta.constants.tsx
  components/base/HeadWithMeta/HeadWithMeta.tsx
  components/base/Snackbar/Snackbar.tsx
  components/base/Snackbar/useSnackbar.ts
  hooks/useMapClickHandlers.ts
  hooks/useUrlPath.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  public/icons/base-og-img.png
  public/robots.txt
Labels: kurala-uygun-pr

#605 feat(#594): Zaman filtresi eklenmesi
  components/UI/FilterTimeMenu/FilterTimeMenu.tsx
  components/UI/FooterBanner/FooterBanner.module.css
  components/UI/SitesIcon/Icons.tsx
  pages/index.tsx
Labels: kurala-uygun-pr

#658 refactor(#642): Channel parametresine göre Drawer contentinde içerik gösterme
  components/UI/ClusterPopup/ClusterPopup.tsx
  components/UI/Drawer/Drawer.tsx
  components/UI/Drawer/components/Content.tsx
  components/UI/Drawer/components/MapButtons.tsx
  components/UI/Drawer/components/channels/FeedChannelGeneric.tsx
  components/UI/Drawer/components/channels/FeedContent.tsx
  components/UI/Drawer/components/channels/babala/FeedChannelBabala.module.css
  components/UI/Drawer/components/channels/babala/FeedChannelBabala.tsx
  components/UI/Drawer/components/channels/twitter/EmbedTweet.tsx
  components/UI/Drawer/components/channels/twitter/FeedChannelTwitter.module.css
  components/UI/Drawer/components/channels/twitter/FeedChannelTwitter.tsx
  components/UI/Drawer/components/channels/twitter/PlaceholderTweet.tsx
  components/UI/Drawer/components/channels/twitter/TwitterLogo.tsx
  components/UI/Drawer/components/types.ts
  mocks/TypesAreasEndpoint.ts
  mocks/types.ts
  utils/dataTransformer.ts
Labels: kurala-uygun-pr

#564 feat (#556): keep user's last info localstorage
  components/UI/Map/ClusterGroup.tsx
  components/UI/Map/LeafletMap.tsx
  components/UI/Map/utils.ts
  components/base/HeadWithMeta/HeadWithMeta.tsx
Labels: kurala-uygun-pr

#603 fix(#601): google translate crash fix
  pages/_document.tsx
  pages/index.tsx
Labels: kurala-uygun-pr

#674 feat(#654): add error boundary
  components/UI/Maintenance/Maintenance.module.css
  components/UI/Maintenance/Maintenance.tsx
  components/base/ErrorBoundary/index.tsx
  errors/index.ts
  pages/404.tsx
  pages/_app.tsx
  pages/_error.tsx
  pages/index.tsx
  styles/Home.module.css
  styles/global.css
Labels: kurala-uygun-pr

#668 fix(#657): remove cluster max zoom level
  components/UI/Map/ClusterGroup.tsx
Labels: kurala-uygun-pr

#644 fix(#639): unnecessary requests on load with undefined
  pages/index.tsx
Labels: kurala-uygun-pr

#688 fix(#656): Duplicated clusters grouped
  components/UI/Map/LayerControl.tsx
Labels: kurala-uygun-pr

#697 fix(#541): harita - google maps link degisimi
  components/UI/Drawer/components/MapButtons.tsx
Labels: kurala-uygun-pr

#710 Feat(#702) add i18n support
  components/UI/FilterMenu/FilterMenu.tsx
  components/UI/FilterMenu/FilterMenuButton.tsx
  components/UI/FilterMenu/FilterReasoningMenu.tsx
  components/UI/FilterMenu/FilterTimeMenu.tsx
  components/UI/I18n/LocaleSwitch.module.css
  components/UI/I18n/LocaleSwitch.tsx
  next-i18next.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/locales/en/common.json
  public/locales/tr/common.json
  styles/Home.module.css
  yarn.lock
Labels: kurala-uygun-pr

#687 refactor(#686): babala feed content improvements
  components/UI/Drawer/components/channels/babala/FeedChannelBabala.tsx
  components/UI/Drawer/components/types.ts
  mocks/TypesAreasEndpoint.ts
  utils/dataTransformer.ts
Labels: kurala-uygun-pr

#744 feat(#742): add translations for error pages
  pages/404.tsx
  pages/_error.tsx
  public/locales/en/error.json
  public/locales/tr/error.json
Labels: kurala-uygun-pr

#766 fix: remove getInitialProps from _error to prevent build errors
  pages/_error.tsx
Labels: emergency

#741 feat(690): dynamic timestamp filter option
  components/UI/FilterMenu/FilterTimeMenu.tsx
  pages/index.tsx
Labels: question, kurala-uygun-pr, tested

#779 update getTimeAgo method #778
  utils/date.ts
Labels: kurala-uygun-pr

#731 feat(#724): New layer drawer and base layer selection
  components/UI/Drawer/Drawer.tsx
  components/UI/Drawer/components/Content.tsx
  components/UI/Drawer/components/LayerButton.module.css
  components/UI/Drawer/components/LayerButton.tsx
  components/UI/Drawer/components/LayerContent.tsx
  components/UI/FilterMenu/FilterMenu.tsx
  components/UI/Map/ClusterGroup.tsx
  components/UI/Map/LayerControl.tsx
  components/UI/Map/LeafletMap.tsx
  components/UI/Map/ViewControl.tsx
  public/icons/stack-line.svg
  public/images/bubblemap.png
  public/images/default.png
  public/images/heatmap.png
  public/images/markers.png
  public/images/satellite.png
  public/images/terrain.png
  public/locales/en/home.json
  public/locales/tr/home.json
  stores/mapStore.tsx
Labels: kurala-uygun-pr, UX/UI, test-failed

#788 fix add minutes
  utils/date.ts
Labels: kurala-uygun-pr

#787 fix: detail drawer is full width on desktop
  components/UI/Drawer/components/Content.tsx
Labels: bug, approved, waiting-test

#762 fix(#750): check babala reason is not NaN
  components/UI/Drawer/components/channels/babala/FeedChannelBabala.tsx
Labels: kurala-uygun-pr, tested

#780 fix(#777): locale switch menu doesn't close after select a locale
  components/UI/I18n/LocaleSwitch.tsx
Labels: kurala-uygun-pr

#785 (feat: #663): keep marker click history and grayscale previously clicked markers
  components/UI/Map/ClusterGroup.tsx
  components/UI/Map/LayerControl.tsx
  components/UI/Map/LeafletMap.tsx
  components/UI/Map/Map.module.css
  components/UI/Map/utils.ts
  hooks/useMapClickHandlers.ts
  mocks/types.ts
  package.json
  pages/index.tsx
  stores/mapStore.tsx
  utils/dataTransformer.ts
  yarn.lock
Labels: kurala-uygun-pr

#758 feat(730): we should add multiple language alternatives for seo
  components/base/HeadWithMeta/HeadWithMeta.constants.tsx
  components/base/HeadWithMeta/HeadWithMeta.tsx
  pages/_error.tsx
Labels: kurala-uygun-pr, waiting-test

#805 feat(#768): copy help content
  components/UI/Drawer/components/channels/twitter/FeedChannelTwitter.tsx
  public/locales/en/home.json
  public/locales/tr/home.json
Labels: kurala-uygun-pr

#791 fix(#769): afet icon added
  components/UI/SitesIcon/Icons.module.css
  components/UI/SitesIcon/Icons.tsx
  public/icons/afetBilgiIcon.svg
Labels: kurala-uygun-pr

#800 twitter reason add #798
  components/UI/Drawer/components/channels/babala/FeedChannelBabala.tsx
  components/UI/Drawer/components/channels/twitter/EmbedTweet.tsx
  components/UI/Drawer/components/channels/twitter/FeedChannelTwitter.tsx
  components/UI/Drawer/components/channels/twitter/PlaceholderTweet.tsx
  utils/helpers.ts
Labels: kurala-uygun-pr

#870 fix(#866): filter empty reason strings from list
  components/UI/Drawer/components/channels/twitter/PlaceholderTweet.tsx
Labels: waiting-test

#872 feat: data source banner text update for both languages
  components/UI/FooterBanner/FooterBanner.module.css
  public/locales/en/common.json
  public/locales/tr/common.json
Labels: waiting-test

#874 Fix (#752) - Id disappearing bug
  components/UI/Map/LeafletMap.tsx
Labels: waiting-test

#875 fix(#845): points disappearing issue fixed by expanding coordinates
  components/UI/Map/LeafletMap.tsx
  utils/constants.ts
Labels: waiting-test

#821 docs: project story
  README.md
  README_ENG.md
  STORY/STORY-BEHIND.md
  STORY/afetharita.png
  STORY/afetharita2.png
  STORY/afetharita3.png
  STORY/afetharita4.png
  STORY/discord.png
Labels: documentation, help wanted, wip

#933 fix(#926): Fix incorrect uppercase in filter Menu
  components/UI/FilterMenu/CommonFilterMenu.tsx
Labels: tested

#927 prod
  components/UI/Drawer/components/Content.tsx
  components/UI/Drawer/components/LayerContent.tsx
  components/UI/Drawer/components/MapButtons.tsx
  components/UI/Drawer/components/OtherRecordsInSameLocation.tsx
  components/UI/Drawer/components/channels/DrawerContent.tsx
  components/UI/Drawer/components/channels/FeedChannelTeleteyit.tsx
  components/UI/Drawer/components/channels/FeedContent.tsx
  components/UI/Drawer/components/channels/drawerContent.module.css
  components/UI/Drawer/components/channels/twitter/FeedChannelAhbap.tsx
  components/UI/Drawer/components/types.ts
  components/UI/FilterMenu/CommonFilterMenu.tsx
  components/UI/Map/LayerControl.tsx
  components/UI/Map/LeafletMap.tsx
  components/UI/Map/TeleteyitClusterGroup.tsx
  components/base/HeadWithMeta/HeadWithMeta.tsx
  hooks/useMapClickHandlers.ts
  hooks/useVerifiedLocations.tsx
  package.json
  pages/index.tsx
  public/images/icon-12.png
  public/images/icon-13.png
  public/images/teleteyit.png
  public/images/uydu.png
  public/locales/en/home.json
  public/locales/tr/home.json
  stores/mapStore.tsx
  tsconfig.json
  types/dirty-json.d.ts
  utils/constants.ts
  utils/helpers.ts
  yarn.lock
Labels: emergency, p0, tested

#946 feat: make locale persistent
  pages/_app.tsx
  utils/cookie.ts
Labels: approved, p1

#983 feat: implementnew channel guvenli bolgeler ve oteller channel
  components/UI/Drawer/components/Content.tsx
  components/UI/Drawer/components/LayerContent.tsx
  components/UI/Drawer/components/MapButtons.tsx
  components/UI/Drawer/components/OtherRecordsInSameLocation.tsx
  components/UI/Drawer/components/channels/FeedChannelSafePlaces.tsx
  components/UI/Drawer/components/channels/FeedContent.tsx
  components/UI/Drawer/components/types.ts
  components/UI/Map/LayerControl.tsx
  components/UI/Map/LeafletMap.tsx
  components/UI/Map/SafePlacesClusterGroup.tsx
  hooks/useVerifiedLocations.tsx
  pages/index.tsx
  public/images/icon-16.png
  stores/mapStore.tsx
  utils/constants.ts
Labels: approved, p0, waiting-test

#1133 feat: add overflow scroll to helpview
  src/newlayout/components/HelpViewComponent/HelpViewComponent.tsx
Labels: tested

#1135 fix: hide source button if tweet_id is null
  src/components/UI/Drawer/NewDrawer.tsx
Labels: tested

#1128 fix: help view translations
  src/newlayout/components/HelpViewComponent/HelpViewComponent.tsx
  src/newlayout/components/HelpViewComponent/data.tsx
  src/pages/index.tsx
Labels: tested

#1140 fix: use static reasons
  src/services/ApiClient.ts
Labels: waiting-test

#1163 feat: enable data from teyit_enkaz channel
  src/hooks/useVerifiedLocations.tsx
  src/types/index.ts
Labels: tested

#1165 deploy rc 🚀
  .github/ISSUE_TEMPLATE/new_data_request.yaml
  src/components/UI/Map/GenericClusterGroup.tsx
  src/components/UI/Map/MapMarker.module.css
  src/hooks/useVerifiedLocations.tsx
  src/newlayout/components/map/MapContent.tsx
  src/stores/visitedMarkersStore.ts
  src/types/index.ts
Labels: tested

#1169 feat: add teyit_yardim data request
  src/hooks/useVerifiedLocations.tsx
  src/types/index.ts
Labels: waiting-test

#1174 fix: alakasiz reason has been filtered from twitter content section
  src/components/UI/Drawer/components/channels/twitter/PlaceholderTweet.tsx
Labels: tested

#1176 fix: user guide should be scrollable for different desktop sizes
  src/newlayout/components/UserGuide/UserGuide.tsx
Labels: tested

#1168 feat: add depremio data request
  src/hooks/useVerifiedLocations.tsx
  src/types/index.ts
Labels: tested

#1180 refactor: add scan area button disabled state
  src/newlayout/components/Button/Cooldown.tsx
  src/utils/helpers.ts
Labels: tested

#1173 fix: channel names on feed content
  src/components/UI/Drawer/components/channels/FeedChannelSatellite.tsx
  src/components/UI/Drawer/components/channels/FeedChannelTeleteyit.tsx
Labels: test-failed

#1177 deploy rc 🚀
  src/components/DoubleClickStopPropagation.tsx
  src/components/UI/Drawer/NewDrawer.tsx
  src/components/UI/Drawer/components/Content.tsx
  src/components/UI/Drawer/components/channels/FeedChannelSatellite.tsx
  src/components/UI/Drawer/components/channels/FeedChannelTeleteyit.tsx
  src/components/UI/Drawer/components/channels/FeedContent.tsx
  src/components/UI/Drawer/components/channels/twitter/EmbedTweet.tsx
  src/components/UI/Drawer/components/channels/twitter/PlaceholderTweet.tsx
  src/components/UI/Drawer/types.ts
  src/hooks/useLocation.ts
  src/hooks/useMapEvents.ts
  src/hooks/useVerifiedLocations.tsx
  src/hooks/useWindowSize.ts
  src/newlayout/components/Attributions/Attributions.module.css
  src/newlayout/components/Attributions/Attributions.tsx
  src/newlayout/components/Button/Cooldown.tsx
  src/newlayout/components/Button/Filter.tsx
  src/newlayout/components/Filter/Filter.tsx
  src/newlayout/components/LocaleSwitch/LocaleSwitch.tsx
  src/newlayout/components/MTMLView/MTMLView.tsx
  src/newlayout/components/MTMLView/types.ts
  src/newlayout/components/Map/Content.tsx
  src/newlayout/components/Map/Controls/ButtonControl.tsx
  src/newlayout/components/Map/Controls/Control.tsx
  src/newlayout/components/Map/Controls/LayerButton.tsx
  src/newlayout/components/Map/Controls/index.tsx
  src/newlayout/components/Map/Dynamic.tsx
  src/newlayout/components/Map/index.tsx
  src/newlayout/components/UserGuide/UserGuide.tsx
  src/newlayout/components/UserGuide/data.tsx
  src/pages/index.tsx
  src/services/responses/ahbap.ts
  src/services/responses/babala.ts
  src/services/responses/depremio.ts
  src/services/responses/food.ts
  src/services/responses/hospital.ts
  src/services/responses/index.ts
  src/services/responses/pharmacy.ts
  src/services/responses/safe-place.ts
  src/services/responses/sahra.ts
  src/services/responses/satellite.ts
  src/services/responses/teleteyit.ts
  src/services/responses/teyit-enkaz.ts
  src/services/responses/teyit-yardim.ts
  src/services/responses/twitter.ts
  src/types/index.ts
  src/utils/geometry.ts
Labels: waiting-test

#1179 feat: implement generic feed content translations
  .prettierignore
  public/images/icon-21.png
  public/locales/en/common.json
  public/locales/en/error.json
  public/locales/en/home.json
  public/locales/tr/common.json
  public/locales/tr/error.json
  public/locales/tr/home.json
  public/manifest.json
  src/components/Drawer/components/LayerContent.tsx
  src/components/Drawer/components/channels/FeedChannelGeneric.tsx
  src/components/Drawer/components/channels/FeedChannelPharmacy.tsx
  src/components/Drawer/components/channels/FeedChannelSafePlaces.tsx
  src/components/Drawer/components/channels/FeedChannelSahraKitchen.tsx
  src/components/Drawer/components/channels/FeedChannelSatellite.tsx
  src/components/Drawer/components/channels/FeedContent.tsx
  src/components/Drawer/components/channels/babala/FeedChannelBabala.tsx
  src/components/Drawer/components/channels/twitter/FeedChannelAhbap.tsx
  src/components/Drawer/components/channels/twitter/FeedChannelTwitter.tsx
  src/components/Drawer/types.ts
  src/hooks/useVerifiedLocations.tsx
  src/services/responses/food.ts
  src/services/responses/index.ts
  src/services/responses/sahra.ts
  src/services/responses/teyit-enkaz.ts
  src/stores/mapStore.ts
  src/types/index.ts
  src/utils/constants.ts
Labels: tested

#1188 refactor(#1186): named exports
  src/components/DoubleClickStopPropagation.tsx
  src/components/Drawer/NewDrawer.tsx
  src/components/Drawer/components/MapButtons.tsx
  src/components/Drawer/components/channels/FeedContent.tsx
  src/components/Drawer/components/channels/babala/FeedChannelBabala.tsx
  src/components/Drawer/components/channels/twitter/EmbedTweet.tsx
  src/components/Drawer/components/channels/twitter/FeedChannelTwitter.tsx
  src/components/Drawer/components/channels/twitter/PlaceholderTweet.tsx
  src/components/Drawer/components/channels/twitter/TwitterLogo.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/HeadWithMeta/HeadWithMeta.tsx
  src/components/Map/Content.tsx
  src/components/Map/Controls/ButtonControl.tsx
  src/components/Map/Controls/index.tsx
  src/components/Map/Map.tsx
  src/components/Map/index.tsx
  src/components/Snackbar/Snackbar.tsx
  src/components/Snackbar/SnackbarCloseButton.tsx
  src/components/Snackbar/index.ts
  src/components/Snackbar/useSnackbar.ts
  src/components/Tag/Tag.tsx
  src/hooks/useDefaultCenter.tsx
  src/hooks/useDefaultZoom.tsx
  src/hooks/useFetchLocations.ts
  src/hooks/useLocation.ts
  src/hooks/usePersistentLangauge.ts
  src/hooks/useVerifiedLocations.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/feeds/areas.ts
  src/pages/index.tsx
  src/utils/createEmotionCache.ts
Labels: tested

#1197 refactor: update marker icons
  public/images/icon-7.png
  public/images/icon-ahbap.png
  public/images/icon-babala.png
  public/images/icon-deprem.io.png
  public/images/icon-enkaz.png
  public/images/icon-generic.png
  public/images/icon-twitter.png
  public/images/icon-yardim.png
  src/components/Map/Dynamic.tsx
  src/services/responses/ahbap.ts
  src/services/responses/babala.ts
  src/services/responses/depremio.ts
  src/services/responses/teyit-enkaz.ts
  src/services/responses/teyit-yardim.ts
  src/services/responses/twitter.ts
Labels: waiting-test

#1199 fix: translation issues
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/tr/common.json
  public/locales/tr/home.json
  src/components/Attributions/Attributions.module.css
  src/components/Attributions/Attributions.tsx
  src/components/Filter/Filter.tsx
  src/services/ApiClient.ts
Labels: test-failed

#1195 feat: implement filters for new user interface
  package.json
  public/locales/en/home.json
  public/locales/tr/home.json
  src/components/Drawer/NewDrawer.tsx
  src/components/Filter/Filter.tsx
  src/components/Filter/FilterControl.tsx
  src/components/Filter/FilterHeader.tsx
  src/components/MTMLView/MTMLView.tsx
  src/components/Map/Cluster/GenericClusterGroup.tsx
  src/components/Map/Content.tsx
  src/components/Map/Controls/index.tsx
  src/components/Map/LayerControl.tsx
  src/components/Map/utils.ts
  src/features/location-categories/category-filters.ts
  src/features/location-categories/disaster-victims/FilterDisasterVictim.tsx
  src/features/location-categories/disaster-victims/useDisasterVictimFilter.ts
  src/features/location-categories/disaster-victims/useDisasterVictimsData.ts
  src/features/location-categories/help-requests/FilterHelpRequest.tsx
  src/features/location-categories/help-requests/useHelpRequestFilter.ts
  src/features/location-categories/help-requests/useHelpRequestsData.ts
  src/features/location-categories/index.ts
  src/features/location-categories/services/FilterService.tsx
  src/features/location-categories/services/useServiceFilter.ts
  src/features/location-categories/services/useServicesData.ts
  src/features/location-categories/types.ts
  src/hooks/useMapEvents.ts
  src/pages/index.tsx
  src/services/ApiClient.ts
  src/services/dataFetcher.ts
  src/stores/mapGeographyStore.ts
  src/utils/date.ts
  src/utils/zustand.ts
  yarn.lock
Labels: waiting-test

#1207 rc deploy 🍻
  src/components/Map/Content.tsx
Labels: waiting-test
